//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malatya.AsisService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://asis-services.com/", ConfigurationName="AsisService.AsisServiceSoap")]
    public interface AsisServiceSoap {
        
        // CODEGEN: Generating message contract since message StopsStationsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/StopsStations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.StopsStationsResponse StopsStations(Malatya.AsisService.StopsStationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/StopsStations", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.StopsStationsResponse> StopsStationsAsync(Malatya.AsisService.StopsStationsRequest request);
        
        // CODEGEN: Generating message contract since message LinesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Lines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.LinesResponse Lines(Malatya.AsisService.LinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Lines", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.LinesResponse> LinesAsync(Malatya.AsisService.LinesRequest request);
        
        // CODEGEN: Generating message contract since message LineDirectionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/LineDirections", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.LineDirectionsResponse LineDirections(Malatya.AsisService.LineDirectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/LineDirections", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.LineDirectionsResponse> LineDirectionsAsync(Malatya.AsisService.LineDirectionsRequest request);
        
        // CODEGEN: Generating message contract since message DepartingTimesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/DepartingTimes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.DepartingTimesResponse DepartingTimes(Malatya.AsisService.DepartingTimesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/DepartingTimes", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.DepartingTimesResponse> DepartingTimesAsync(Malatya.AsisService.DepartingTimesRequest request);
        
        // CODEGEN: Generating message contract since message RealTimeDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/RealTimeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.RealTimeDataResponse RealTimeData(Malatya.AsisService.RealTimeDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/RealTimeData", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.RealTimeDataResponse> RealTimeDataAsync(Malatya.AsisService.RealTimeDataRequest request);
        
        // CODEGEN: Generating message contract since message RealDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/RealData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.RealDataResponse RealData(Malatya.AsisService.RealDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/RealData", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.RealDataResponse> RealDataAsync(Malatya.AsisService.RealDataRequest request);
        
        // CODEGEN: Generating message contract since message SchedulesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Schedules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.SchedulesResponse Schedules(Malatya.AsisService.SchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Schedules", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.SchedulesResponse> SchedulesAsync(Malatya.AsisService.SchedulesRequest request);
        
        // CODEGEN: Generating message contract since message CheckBalanceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/CheckBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.CheckBalanceResponse CheckBalance(Malatya.AsisService.CheckBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/CheckBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.CheckBalanceResponse> CheckBalanceAsync(Malatya.AsisService.CheckBalanceRequest request);
        
        // CODEGEN: Generating message contract since message CheckCurrentRouteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/CheckCurrentRoute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.CheckCurrentRouteResponse CheckCurrentRoute(Malatya.AsisService.CheckCurrentRouteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/CheckCurrentRoute", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.CheckCurrentRouteResponse> CheckCurrentRouteAsync(Malatya.AsisService.CheckCurrentRouteRequest request);
        
        // CODEGEN: Generating message contract since message PointOfSaleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/PointOfSale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.PointOfSaleResponse PointOfSale(Malatya.AsisService.PointOfSaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/PointOfSale", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.PointOfSaleResponse> PointOfSaleAsync(Malatya.AsisService.PointOfSaleRequest request);
        
        // CODEGEN: Generating message contract since message CicoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Cico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.CicoResponse Cico(Malatya.AsisService.CicoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Cico", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.CicoResponse> CicoAsync(Malatya.AsisService.CicoRequest request);
        
        // CODEGEN: Generating message contract since message PricetableRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Pricetable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.PricetableResponse Pricetable(Malatya.AsisService.PricetableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/Pricetable", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.PricetableResponse> PricetableAsync(Malatya.AsisService.PricetableRequest request);
        
        // CODEGEN: Generating message contract since message RawDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/RawData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.RawDataResponse RawData(Malatya.AsisService.RawDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/RawData", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.RawDataResponse> RawDataAsync(Malatya.AsisService.RawDataRequest request);
        
        // CODEGEN: Generating message contract since message TotalProceedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/TotalProceed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Malatya.AsisService.TotalProceedResponse TotalProceed(Malatya.AsisService.TotalProceedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://asis-services.com/TotalProceed", ReplyAction="*")]
        System.Threading.Tasks.Task<Malatya.AsisService.TotalProceedResponse> TotalProceedAsync(Malatya.AsisService.TotalProceedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class WSRequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class RawDataResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cardTypeField;
        
        private System.DateTime dateField;
        
        private decimal deductField;
        
        private string grupCodeField;
        
        private System.DateTime insertDateField;
        
        private string plateField;
        
        private long recIdField;
        
        private string routeCodeField;
        
        private int tripIdField;
        
        private int valNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Deduct {
            get {
                return this.deductField;
            }
            set {
                this.deductField = value;
                this.RaisePropertyChanged("Deduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GrupCode {
            get {
                return this.grupCodeField;
            }
            set {
                this.grupCodeField = value;
                this.RaisePropertyChanged("GrupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
                this.RaisePropertyChanged("InsertDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Plate {
            get {
                return this.plateField;
            }
            set {
                this.plateField = value;
                this.RaisePropertyChanged("Plate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
                this.RaisePropertyChanged("RecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RouteCode {
            get {
                return this.routeCodeField;
            }
            set {
                this.routeCodeField = value;
                this.RaisePropertyChanged("RouteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int TripId {
            get {
                return this.tripIdField;
            }
            set {
                this.tripIdField = value;
                this.RaisePropertyChanged("TripId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ValNumber {
            get {
                return this.valNumberField;
            }
            set {
                this.valNumberField = value;
                this.RaisePropertyChanged("ValNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class ApiResponseOfRawDataResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private RawDataResult[] resultField;
        
        private int statusCodeField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public RawDataResult[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class PricetableResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aciklamaField;
        
        private decimal fiyatField;
        
        private string hatKoduField;
        
        private string karttipiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal fiyat {
            get {
                return this.fiyatField;
            }
            set {
                this.fiyatField = value;
                this.RaisePropertyChanged("fiyat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hatKodu {
            get {
                return this.hatKoduField;
            }
            set {
                this.hatKoduField = value;
                this.RaisePropertyChanged("hatKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string karttipi {
            get {
                return this.karttipiField;
            }
            set {
                this.karttipiField = value;
                this.RaisePropertyChanged("karttipi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class ApiResponseOfPricetableResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private PricetableResult[] resultField;
        
        private int statusCodeField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public PricetableResult[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class CicoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime checkInField;
        
        private System.DateTime checkOutField;
        
        private string plateField;
        
        private string routeCodeField;
        
        private int stopOrderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime CheckIn {
            get {
                return this.checkInField;
            }
            set {
                this.checkInField = value;
                this.RaisePropertyChanged("CheckIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CheckOut {
            get {
                return this.checkOutField;
            }
            set {
                this.checkOutField = value;
                this.RaisePropertyChanged("CheckOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Plate {
            get {
                return this.plateField;
            }
            set {
                this.plateField = value;
                this.RaisePropertyChanged("Plate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RouteCode {
            get {
                return this.routeCodeField;
            }
            set {
                this.routeCodeField = value;
                this.RaisePropertyChanged("RouteCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int StopOrderId {
            get {
                return this.stopOrderIdField;
            }
            set {
                this.stopOrderIdField = value;
                this.RaisePropertyChanged("StopOrderId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class ApiResponseOfCicoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private CicoResult[] resultField;
        
        private int statusCodeField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public CicoResult[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class PointOfSaleResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string descriptionField;
        
        private string latitudeField;
        
        private string lontitudeField;
        
        private string posCodeField;
        
        private string telField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lontitude {
            get {
                return this.lontitudeField;
            }
            set {
                this.lontitudeField = value;
                this.RaisePropertyChanged("lontitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string posCode {
            get {
                return this.posCodeField;
            }
            set {
                this.posCodeField = value;
                this.RaisePropertyChanged("posCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class ApiResponseOfPointOfSaleResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private PointOfSaleResult[] resultField;
        
        private int statusCodeField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public PointOfSaleResult[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://asis-services.com/")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet dataField;
        
        private int resultField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StopsStations", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class StopsStationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        public StopsStationsRequest() {
        }
        
        public StopsStationsRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StopsStationsResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class StopsStationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response StopsStationsResult;
        
        public StopsStationsResponse() {
        }
        
        public StopsStationsResponse(Malatya.AsisService.Response StopsStationsResult) {
            this.StopsStationsResult = StopsStationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lines", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class LinesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        public LinesRequest() {
        }
        
        public LinesRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LinesResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class LinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response LinesResult;
        
        public LinesResponse() {
        }
        
        public LinesResponse(Malatya.AsisService.Response LinesResult) {
            this.LinesResult = LinesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LineDirections", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class LineDirectionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        public LineDirectionsRequest() {
        }
        
        public LineDirectionsRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LineDirectionsResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class LineDirectionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response LineDirectionsResult;
        
        public LineDirectionsResponse() {
        }
        
        public LineDirectionsResponse(Malatya.AsisService.Response LineDirectionsResult) {
            this.LineDirectionsResult = LineDirectionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepartingTimes", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class DepartingTimesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=2)]
        public System.DateTime departingDate;
        
        public DepartingTimesRequest() {
        }
        
        public DepartingTimesRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode, System.DateTime departingDate) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
            this.departingDate = departingDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepartingTimesResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class DepartingTimesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response DepartingTimesResult;
        
        public DepartingTimesResponse() {
        }
        
        public DepartingTimesResponse(Malatya.AsisService.Response DepartingTimesResult) {
            this.DepartingTimesResult = DepartingTimesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RealTimeData", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class RealTimeDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        public RealTimeDataRequest() {
        }
        
        public RealTimeDataRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RealTimeDataResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class RealTimeDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response RealTimeDataResult;
        
        public RealTimeDataResponse() {
        }
        
        public RealTimeDataResponse(Malatya.AsisService.Response RealTimeDataResult) {
            this.RealTimeDataResult = RealTimeDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RealData", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class RealDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        public RealDataRequest() {
        }
        
        public RealDataRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RealDataResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class RealDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response RealDataResult;
        
        public RealDataResponse() {
        }
        
        public RealDataResponse(Malatya.AsisService.Response RealDataResult) {
            this.RealDataResult = RealDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Schedules", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class SchedulesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=2)]
        public System.DateTime scheduleDate;
        
        public SchedulesRequest() {
        }
        
        public SchedulesRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode, System.DateTime scheduleDate) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
            this.scheduleDate = scheduleDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SchedulesResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class SchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response SchedulesResult;
        
        public SchedulesResponse() {
        }
        
        public SchedulesResponse(Malatya.AsisService.Response SchedulesResult) {
            this.SchedulesResult = SchedulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckBalance", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class CheckBalanceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string cardNumber;
        
        public CheckBalanceRequest() {
        }
        
        public CheckBalanceRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string cardNumber) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.cardNumber = cardNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckBalanceResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class CheckBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response CheckBalanceResult;
        
        public CheckBalanceResponse() {
        }
        
        public CheckBalanceResponse(Malatya.AsisService.Response CheckBalanceResult) {
            this.CheckBalanceResult = CheckBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCurrentRoute", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class CheckCurrentRouteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string plate;
        
        public CheckCurrentRouteRequest() {
        }
        
        public CheckCurrentRouteRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string plate) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.plate = plate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCurrentRouteResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class CheckCurrentRouteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response CheckCurrentRouteResult;
        
        public CheckCurrentRouteResponse() {
        }
        
        public CheckCurrentRouteResponse(Malatya.AsisService.Response CheckCurrentRouteResult) {
            this.CheckCurrentRouteResult = CheckCurrentRouteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PointOfSale", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class PointOfSaleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        public PointOfSaleRequest() {
        }
        
        public PointOfSaleRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PointOfSaleResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class PointOfSaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.ApiResponseOfPointOfSaleResult PointOfSaleResult;
        
        public PointOfSaleResponse() {
        }
        
        public PointOfSaleResponse(Malatya.AsisService.ApiResponseOfPointOfSaleResult PointOfSaleResult) {
            this.PointOfSaleResult = PointOfSaleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cico", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class CicoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public long tripId;
        
        public CicoRequest() {
        }
        
        public CicoRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, long tripId) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.tripId = tripId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CicoResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class CicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.ApiResponseOfCicoResult CicoResult;
        
        public CicoResponse() {
        }
        
        public CicoResponse(Malatya.AsisService.ApiResponseOfCicoResult CicoResult) {
            this.CicoResult = CicoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pricetable", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class PricetableRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public string lineCode;
        
        public PricetableRequest() {
        }
        
        public PricetableRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.lineCode = lineCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PricetableResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class PricetableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.ApiResponseOfPricetableResult PricetableResult;
        
        public PricetableResponse() {
        }
        
        public PricetableResponse(Malatya.AsisService.ApiResponseOfPricetableResult PricetableResult) {
            this.PricetableResult = PricetableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RawData", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class RawDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public long valRecordId;
        
        public RawDataRequest() {
        }
        
        public RawDataRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, long valRecordId) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.valRecordId = valRecordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RawDataResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class RawDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.ApiResponseOfRawDataResult RawDataResult;
        
        public RawDataResponse() {
        }
        
        public RawDataResponse(Malatya.AsisService.ApiResponseOfRawDataResult RawDataResult) {
            this.RawDataResult = RawDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TotalProceed", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class TotalProceedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://asis-services.com/")]
        public Malatya.AsisService.WSRequestHeader WSRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public string cityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=1)]
        public System.DateTime firstDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=2)]
        public System.DateTime lastDate;
        
        public TotalProceedRequest() {
        }
        
        public TotalProceedRequest(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, System.DateTime firstDate, System.DateTime lastDate) {
            this.WSRequestHeader = WSRequestHeader;
            this.cityCode = cityCode;
            this.firstDate = firstDate;
            this.lastDate = lastDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TotalProceedResponse", WrapperNamespace="https://asis-services.com/", IsWrapped=true)]
    public partial class TotalProceedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://asis-services.com/", Order=0)]
        public Malatya.AsisService.Response TotalProceedResult;
        
        public TotalProceedResponse() {
        }
        
        public TotalProceedResponse(Malatya.AsisService.Response TotalProceedResult) {
            this.TotalProceedResult = TotalProceedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsisServiceSoapChannel : Malatya.AsisService.AsisServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsisServiceSoapClient : System.ServiceModel.ClientBase<Malatya.AsisService.AsisServiceSoap>, Malatya.AsisService.AsisServiceSoap {
        
        public AsisServiceSoapClient() {
        }
        
        public AsisServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsisServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsisServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsisServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.StopsStationsResponse Malatya.AsisService.AsisServiceSoap.StopsStations(Malatya.AsisService.StopsStationsRequest request) {
            return base.Channel.StopsStations(request);
        }
        
        public Malatya.AsisService.Response StopsStations(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.StopsStationsRequest inValue = new Malatya.AsisService.StopsStationsRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            Malatya.AsisService.StopsStationsResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).StopsStations(inValue);
            return retVal.StopsStationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.StopsStationsResponse> Malatya.AsisService.AsisServiceSoap.StopsStationsAsync(Malatya.AsisService.StopsStationsRequest request) {
            return base.Channel.StopsStationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.StopsStationsResponse> StopsStationsAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.StopsStationsRequest inValue = new Malatya.AsisService.StopsStationsRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).StopsStationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.LinesResponse Malatya.AsisService.AsisServiceSoap.Lines(Malatya.AsisService.LinesRequest request) {
            return base.Channel.Lines(request);
        }
        
        public Malatya.AsisService.Response Lines(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode) {
            Malatya.AsisService.LinesRequest inValue = new Malatya.AsisService.LinesRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            Malatya.AsisService.LinesResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).Lines(inValue);
            return retVal.LinesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.LinesResponse> Malatya.AsisService.AsisServiceSoap.LinesAsync(Malatya.AsisService.LinesRequest request) {
            return base.Channel.LinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.LinesResponse> LinesAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode) {
            Malatya.AsisService.LinesRequest inValue = new Malatya.AsisService.LinesRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).LinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.LineDirectionsResponse Malatya.AsisService.AsisServiceSoap.LineDirections(Malatya.AsisService.LineDirectionsRequest request) {
            return base.Channel.LineDirections(request);
        }
        
        public Malatya.AsisService.Response LineDirections(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.LineDirectionsRequest inValue = new Malatya.AsisService.LineDirectionsRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            Malatya.AsisService.LineDirectionsResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).LineDirections(inValue);
            return retVal.LineDirectionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.LineDirectionsResponse> Malatya.AsisService.AsisServiceSoap.LineDirectionsAsync(Malatya.AsisService.LineDirectionsRequest request) {
            return base.Channel.LineDirectionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.LineDirectionsResponse> LineDirectionsAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.LineDirectionsRequest inValue = new Malatya.AsisService.LineDirectionsRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).LineDirectionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.DepartingTimesResponse Malatya.AsisService.AsisServiceSoap.DepartingTimes(Malatya.AsisService.DepartingTimesRequest request) {
            return base.Channel.DepartingTimes(request);
        }
        
        public Malatya.AsisService.Response DepartingTimes(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode, System.DateTime departingDate) {
            Malatya.AsisService.DepartingTimesRequest inValue = new Malatya.AsisService.DepartingTimesRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            inValue.departingDate = departingDate;
            Malatya.AsisService.DepartingTimesResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).DepartingTimes(inValue);
            return retVal.DepartingTimesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.DepartingTimesResponse> Malatya.AsisService.AsisServiceSoap.DepartingTimesAsync(Malatya.AsisService.DepartingTimesRequest request) {
            return base.Channel.DepartingTimesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.DepartingTimesResponse> DepartingTimesAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode, System.DateTime departingDate) {
            Malatya.AsisService.DepartingTimesRequest inValue = new Malatya.AsisService.DepartingTimesRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            inValue.departingDate = departingDate;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).DepartingTimesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.RealTimeDataResponse Malatya.AsisService.AsisServiceSoap.RealTimeData(Malatya.AsisService.RealTimeDataRequest request) {
            return base.Channel.RealTimeData(request);
        }
        
        public Malatya.AsisService.Response RealTimeData(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.RealTimeDataRequest inValue = new Malatya.AsisService.RealTimeDataRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            Malatya.AsisService.RealTimeDataResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).RealTimeData(inValue);
            return retVal.RealTimeDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.RealTimeDataResponse> Malatya.AsisService.AsisServiceSoap.RealTimeDataAsync(Malatya.AsisService.RealTimeDataRequest request) {
            return base.Channel.RealTimeDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.RealTimeDataResponse> RealTimeDataAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.RealTimeDataRequest inValue = new Malatya.AsisService.RealTimeDataRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).RealTimeDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.RealDataResponse Malatya.AsisService.AsisServiceSoap.RealData(Malatya.AsisService.RealDataRequest request) {
            return base.Channel.RealData(request);
        }
        
        public Malatya.AsisService.Response RealData(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.RealDataRequest inValue = new Malatya.AsisService.RealDataRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            Malatya.AsisService.RealDataResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).RealData(inValue);
            return retVal.RealDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.RealDataResponse> Malatya.AsisService.AsisServiceSoap.RealDataAsync(Malatya.AsisService.RealDataRequest request) {
            return base.Channel.RealDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.RealDataResponse> RealDataAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.RealDataRequest inValue = new Malatya.AsisService.RealDataRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).RealDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.SchedulesResponse Malatya.AsisService.AsisServiceSoap.Schedules(Malatya.AsisService.SchedulesRequest request) {
            return base.Channel.Schedules(request);
        }
        
        public Malatya.AsisService.Response Schedules(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode, System.DateTime scheduleDate) {
            Malatya.AsisService.SchedulesRequest inValue = new Malatya.AsisService.SchedulesRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            inValue.scheduleDate = scheduleDate;
            Malatya.AsisService.SchedulesResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).Schedules(inValue);
            return retVal.SchedulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.SchedulesResponse> Malatya.AsisService.AsisServiceSoap.SchedulesAsync(Malatya.AsisService.SchedulesRequest request) {
            return base.Channel.SchedulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.SchedulesResponse> SchedulesAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode, System.DateTime scheduleDate) {
            Malatya.AsisService.SchedulesRequest inValue = new Malatya.AsisService.SchedulesRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            inValue.scheduleDate = scheduleDate;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).SchedulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.CheckBalanceResponse Malatya.AsisService.AsisServiceSoap.CheckBalance(Malatya.AsisService.CheckBalanceRequest request) {
            return base.Channel.CheckBalance(request);
        }
        
        public Malatya.AsisService.Response CheckBalance(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string cardNumber) {
            Malatya.AsisService.CheckBalanceRequest inValue = new Malatya.AsisService.CheckBalanceRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.cardNumber = cardNumber;
            Malatya.AsisService.CheckBalanceResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).CheckBalance(inValue);
            return retVal.CheckBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.CheckBalanceResponse> Malatya.AsisService.AsisServiceSoap.CheckBalanceAsync(Malatya.AsisService.CheckBalanceRequest request) {
            return base.Channel.CheckBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.CheckBalanceResponse> CheckBalanceAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string cardNumber) {
            Malatya.AsisService.CheckBalanceRequest inValue = new Malatya.AsisService.CheckBalanceRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.cardNumber = cardNumber;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).CheckBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.CheckCurrentRouteResponse Malatya.AsisService.AsisServiceSoap.CheckCurrentRoute(Malatya.AsisService.CheckCurrentRouteRequest request) {
            return base.Channel.CheckCurrentRoute(request);
        }
        
        public Malatya.AsisService.Response CheckCurrentRoute(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string plate) {
            Malatya.AsisService.CheckCurrentRouteRequest inValue = new Malatya.AsisService.CheckCurrentRouteRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.plate = plate;
            Malatya.AsisService.CheckCurrentRouteResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).CheckCurrentRoute(inValue);
            return retVal.CheckCurrentRouteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.CheckCurrentRouteResponse> Malatya.AsisService.AsisServiceSoap.CheckCurrentRouteAsync(Malatya.AsisService.CheckCurrentRouteRequest request) {
            return base.Channel.CheckCurrentRouteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.CheckCurrentRouteResponse> CheckCurrentRouteAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string plate) {
            Malatya.AsisService.CheckCurrentRouteRequest inValue = new Malatya.AsisService.CheckCurrentRouteRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.plate = plate;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).CheckCurrentRouteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.PointOfSaleResponse Malatya.AsisService.AsisServiceSoap.PointOfSale(Malatya.AsisService.PointOfSaleRequest request) {
            return base.Channel.PointOfSale(request);
        }
        
        public Malatya.AsisService.ApiResponseOfPointOfSaleResult PointOfSale(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode) {
            Malatya.AsisService.PointOfSaleRequest inValue = new Malatya.AsisService.PointOfSaleRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            Malatya.AsisService.PointOfSaleResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).PointOfSale(inValue);
            return retVal.PointOfSaleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.PointOfSaleResponse> Malatya.AsisService.AsisServiceSoap.PointOfSaleAsync(Malatya.AsisService.PointOfSaleRequest request) {
            return base.Channel.PointOfSaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.PointOfSaleResponse> PointOfSaleAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode) {
            Malatya.AsisService.PointOfSaleRequest inValue = new Malatya.AsisService.PointOfSaleRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).PointOfSaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.CicoResponse Malatya.AsisService.AsisServiceSoap.Cico(Malatya.AsisService.CicoRequest request) {
            return base.Channel.Cico(request);
        }
        
        public Malatya.AsisService.ApiResponseOfCicoResult Cico(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, long tripId) {
            Malatya.AsisService.CicoRequest inValue = new Malatya.AsisService.CicoRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.tripId = tripId;
            Malatya.AsisService.CicoResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).Cico(inValue);
            return retVal.CicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.CicoResponse> Malatya.AsisService.AsisServiceSoap.CicoAsync(Malatya.AsisService.CicoRequest request) {
            return base.Channel.CicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.CicoResponse> CicoAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, long tripId) {
            Malatya.AsisService.CicoRequest inValue = new Malatya.AsisService.CicoRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.tripId = tripId;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).CicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.PricetableResponse Malatya.AsisService.AsisServiceSoap.Pricetable(Malatya.AsisService.PricetableRequest request) {
            return base.Channel.Pricetable(request);
        }
        
        public Malatya.AsisService.ApiResponseOfPricetableResult Pricetable(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.PricetableRequest inValue = new Malatya.AsisService.PricetableRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            Malatya.AsisService.PricetableResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).Pricetable(inValue);
            return retVal.PricetableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.PricetableResponse> Malatya.AsisService.AsisServiceSoap.PricetableAsync(Malatya.AsisService.PricetableRequest request) {
            return base.Channel.PricetableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.PricetableResponse> PricetableAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, string lineCode) {
            Malatya.AsisService.PricetableRequest inValue = new Malatya.AsisService.PricetableRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.lineCode = lineCode;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).PricetableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.RawDataResponse Malatya.AsisService.AsisServiceSoap.RawData(Malatya.AsisService.RawDataRequest request) {
            return base.Channel.RawData(request);
        }
        
        public Malatya.AsisService.ApiResponseOfRawDataResult RawData(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, long valRecordId) {
            Malatya.AsisService.RawDataRequest inValue = new Malatya.AsisService.RawDataRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.valRecordId = valRecordId;
            Malatya.AsisService.RawDataResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).RawData(inValue);
            return retVal.RawDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.RawDataResponse> Malatya.AsisService.AsisServiceSoap.RawDataAsync(Malatya.AsisService.RawDataRequest request) {
            return base.Channel.RawDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.RawDataResponse> RawDataAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, long valRecordId) {
            Malatya.AsisService.RawDataRequest inValue = new Malatya.AsisService.RawDataRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.valRecordId = valRecordId;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).RawDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Malatya.AsisService.TotalProceedResponse Malatya.AsisService.AsisServiceSoap.TotalProceed(Malatya.AsisService.TotalProceedRequest request) {
            return base.Channel.TotalProceed(request);
        }
        
        public Malatya.AsisService.Response TotalProceed(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, System.DateTime firstDate, System.DateTime lastDate) {
            Malatya.AsisService.TotalProceedRequest inValue = new Malatya.AsisService.TotalProceedRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.firstDate = firstDate;
            inValue.lastDate = lastDate;
            Malatya.AsisService.TotalProceedResponse retVal = ((Malatya.AsisService.AsisServiceSoap)(this)).TotalProceed(inValue);
            return retVal.TotalProceedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Malatya.AsisService.TotalProceedResponse> Malatya.AsisService.AsisServiceSoap.TotalProceedAsync(Malatya.AsisService.TotalProceedRequest request) {
            return base.Channel.TotalProceedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Malatya.AsisService.TotalProceedResponse> TotalProceedAsync(Malatya.AsisService.WSRequestHeader WSRequestHeader, string cityCode, System.DateTime firstDate, System.DateTime lastDate) {
            Malatya.AsisService.TotalProceedRequest inValue = new Malatya.AsisService.TotalProceedRequest();
            inValue.WSRequestHeader = WSRequestHeader;
            inValue.cityCode = cityCode;
            inValue.firstDate = firstDate;
            inValue.lastDate = lastDate;
            return ((Malatya.AsisService.AsisServiceSoap)(this)).TotalProceedAsync(inValue);
        }
    }
}
